### PR TITLE
fix(config): support absolute paths in cardano-node config

### LINKED ISSUE #519: Absolute paths disallowed in `config.json`
(sorry if this is the wrong repo for this issue)

In your `config.json`, if you specify an absolute path

```json
{
    "ByronGenesisFile": "/home/dev/.yaci-cli/local-clusters/default/node/genesis/byron-genesis.json",
}
```

It will fail to recognize this as an absolute path, and instead fail (as it tries to parse it as a relative path)

### PR DESCRIPTION
**Pull request by wolf31o2**
If the given paths to the genesis files in the cardano-node config are absolute, use them. Otherwise, prepend the `config.json` directory to the file names.

Closes #519

### CODE REVIEW

File: config/cardano/node.go [hunk 1]
```diff
@@ -69,9 +70,13 @@ func NewCardanoNodeConfigFromFile(file string) (*CardanoNodeConfig, error) {
 }
 
 func (c *CardanoNodeConfig) loadGenesisConfigs() error {
+	prefix := "/"
 	// Load Byron genesis
 	if c.ByronGenesisFile != "" {
-		byronGenesisPath := path.Join(c.path, c.ByronGenesisFile)
+		byronGenesisPath := c.ByronGenesisFile
+		if !strings.HasPrefix(byronGenesisPath, prefix) {
```
Comment (agaffney) [inline config/cardano/node.go:77]: There's the `path/filepath.IsAbs()` function for this

**Review by agaffney — DISMISSED** [review]

File: config/cardano/node.go (hunk 1 above)
Comment (wolf31o2) [reply config/cardano/node.go]: Neat. Switched to it.

**Review by agaffney — APPROVED** [review]
